name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    name: Code validation
    uses: ./.github/workflows/validate.yml

  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs: validate

  release:
    if: ${{ github.event_name == 'push' }}
    name: Continuous release
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs:
      - validate
      - test
