name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  validate:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    name: Code validation
    uses: ./.github/workflows/validate.yml

  test:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    name: Run tests
    uses: ./.github/workflows/test.yml

  release:
    if: ${{ github.event.workflow_run.event == 'push' }}
    name: Continuous release
    uses: ./.github/workflows/release.yml
