name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    if: github.actor != 'github-actions[bot]'
    name: Code validation
    uses: ./.github/workflows/validate.yml

  test:
    if: github.actor != 'github-actions[bot]'
    name: Run tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs: validate

  docs:
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    name: Generate docs
    uses: ./.github/workflows/docs.yml
    secrets: inherit
    needs:
      - validate
      - test

  release:
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    name: Continuous release
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs:
      - docs
