name: Code Validation

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Compile ts
        run: npm run type

      - name: Run tests
        run: npm run test
